### ISSUE TITLE
Коды ошибок

### ISSUE THREAD

**Issue by thekrotek** [InJapan/russianpost-tracking#5]
Добавьте, пожалуйста, коды ошибок в библиотеку. Например:

```php
throw new RussianPostArgumentException('Incorrect format of tracking number: ' . $trackingNumber, 100);
```
Код обычно постоянен, а сообщение может меняться. Это необходимо для многоязычных сайтов, чтобы можно было отловить код и выдать свое сообщение на нужном языке.

**Comment by maxgashkov** [comment]
Постараюсь добавить ближе к концу недели.

Если нужно быстрее, пришлите пулл-реквест.

**Comment by thekrotek** [comment]
Да нет, мне-то не к спеху, я уже добавил себе коды 100-105 для всех ошибок, кроме cURL. Если в принципе добавите - хорошо будет. Мало ли придется библиотеку обновить у себя - вот чтобы не нужно было заново вносить изменения в нее.

А PR на гитхабе - это жуткий геморой. Я до сих пор не могу понять, как их делать, хотя и инструкции читал, и примеры. Это выше моего понимания, увы :-)

**Comment by stiig** [comment]
@thekrotek если в одном файле изменения, то редактируйте прямо в гитхабе, есть кнопочка Edit, довольно удобно если небольшие изменения
