### ISSUE TITLE
Запрос пачками

### ISSUE THREAD

**Issue by stiig** [InJapan/russianpost-tracking#6]
А почта России не позволяет пачками передавать номера отправлений?

**Comment by mkamois** [comment]
позволяет, но у них для этого другое апи и нужно заключать договор на юр.лицо (по крайней мере в прошлом году мне так ответили), но там на совсем большие пачки похоже рассчитано (1000+ номеров)

**Comment by alexmorbo** [comment]
@mkamois а куда писать?

**Comment by stiig** [comment]
@mkamois поддерживаю вопрос, на юр. лицо имеется возможность заключить

**Comment by mkamois** [comment]
@alexmorbo @stiig да всё на тот же адрес fc@russianpost.ru

**Comment by stiig** [comment]
Или если без юр.лица, может можно как-нибудь в multicurl обернуть это?

**Comment by maxgashkov** [comment]
Эта библиотека — средство сделать трекинг для небольшого проекта «быстро и грязно».

Если у вас такое количество запросов, при котором нужен curl_multi, вам необходимо договориться о доступе с Почтой России напрямую (с заключением договора или как-то еще).

Если вы, несмотря на эту рекомендацию, решите делать параллельные запросы пачками, вы можете самостоятельно исправить исходник, он весьма примитивен.

**Comment by NikKurkov** [comment]
Вероятно, у почты два вида баз - старая и новая. Этот код смотрит на старую версию. 
Пример: трек 10756482010651 на старой версии сайта и по коду из проекта указывает, что посылка еще не вручена. На новой версии сайта Почта России посылка вручена (что соответствует правде).

**Comment by maxgashkov** [comment]
@NikKurkov во-первых, это не относится к теме запроса.

Во-вторых, на новом сайте пока нет спецификации на какой-то другой API. Если вам очень сильно нужен новый трекинг, вы можете парсить HTML-выдачу, однако в этой библиотеке это не будет реализовано:
https://pochta.ru/tracking?barcode=10756482010651

В-третьих, пока даже профессиональные аггрегаторы не подхватили новый трекинг :)
http://gdeposylka.ru/courier/russian-post/tracking/10756482010651

**Comment by NikKurkov** [comment]
Прошу прощения за дезинформацию. На новом сайте информация совпадает. Меня ввело в заблуждение, что там указана информация о вручении (но сейчас я вижу, что она другим цветом, т.е. неактивна и этот информации у почты на самом деле нет).

**Comment by AndrewBerezin** [comment]
На новом сайте есть АПИ для получения запросов пачками - https://tracking.russianpost.ru/specification.
